def build(bld):
    sources = [
        'compact_writer.cpp',
        'indenting_writer.cpp',
        'parser.cpp',
        'raii.cpp',
        'test.cpp',
        'test_util.cpp',
        'validating_filter.cpp',
    ]

    obj = bld.new_task_gen(
        features = 'cxx cprogram',
        source = sources,
        includes = '../src',
        uselib_local = 'jsonxx',
        unit_test = 1,
        target = 'test'
    )

    # This is a bit of a peculiar waf-thing. The build
    # task is automatically configured to run in the
    # default-configuration, but it needs this line in
    # order to build in the debug-configuration:
    obj.clone('debug')
