def build(bld):
    sources = [
        'object_filter.cpp',
        'object_listener.cpp',
        'compact_writer.cpp',
        'null_object_listener.cpp',
        'validating_filter.cpp',
    ]

    bld.new_task_gen(features='cxx cshlib',
                     source=sources,
                     target='jsonxx',
                    )
